services:
  db:
    image: postgres:16
    container_name: sepbe-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sepbe
    ports:
      - '5432:5432'
    volumes:
      - sepbe_db_data:/var/lib/postgresql/data

volumes:
  sepbe_db_data:
